# Generated by Django 4.0.6 on 2022-11-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_date_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('M', 'Media'), ('D', 'Design'), ('MA', 'Marketing'), ('B', 'Backoffice'), ('S', 'Sales'), ('-', 'None')], default='None', max_length=10),
        ),
    ]
