# Generated by Django 4.0.6 on 2022-11-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_priority_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
