# Generated by Django 4.0.6 on 2022-11-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'To do'), ('2', 'In progress'), ('3', 'Awaiting Feedback'), ('4', 'Done')], default='To do', max_length=17),
        ),
        migrations.AddField(
            model_name='todo',
            name='subtasks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.todo'),
        ),
    ]
