# Generated by Django 4.0.6 on 2022-11-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todo_status_todo_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='subtasks',
        ),
    ]
