# Generated by Django 4.0.6 on 2022-11-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task',
            new_name='todo',
        ),
    ]
