# Generated by Django 4.0.6 on 2022-12-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_todo_subtasks_alter_subtask_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='todo',
        ),
        migrations.AlterField(
            model_name='todo',
            name='subtasks',
            field=models.ManyToManyField(to='todo.subtask'),
        ),
    ]
