# Generated by Django 4.0.6 on 2022-12-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_subtask_done_remove_todo_subtasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='done',
        ),
    ]
