# Generated by Django 4.0.6 on 2022-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_remove_subtask_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='todo',
            name='subtasks',
            field=models.ManyToManyField(default=None, to='todo.subtask'),
        ),
    ]
