# Generated by Django 4.0.6 on 2022-12-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_remove_todo_subtasks_todo_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='subtasks',
            field=models.ManyToManyField(default=None, related_name='SubtaskTitle', to='todo.subtask'),
        ),
    ]
