# Generated by Django 4.0.6 on 2022-12-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_todo_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='subtasks',
            field=models.ManyToManyField(default=None, to='todo.subtask'),
        ),
    ]
