# Generated by Django 4.0.6 on 2022-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_alter_todo_subtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='done',
            field=models.CharField(default='False', max_length=30),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='category',
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'To do'), ('2', 'In progress'), ('3', 'Awaiting Feedback'), ('4', 'Done'), ('5', 'Deleted')], default='To do', max_length=17),
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(default=None, to='todo.category'),
        ),
    ]
