# Generated by Django 4.0.6 on 2022-12-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_rename_category_todo_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='categories',
            field=models.ManyToManyField(default=None, related_name='categories', to='todo.category'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='01-01-2000', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='subtasks',
            field=models.ManyToManyField(default=None, related_name='subtasks', to='todo.subtask'),
        ),
    ]
